# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:           Dan Stroot
url:            http://danstroot.com
root:           /       # If publishing to a subdirectory as in http://site.com/project set 'root: /project'
title:          My Personal Blog
rss:            http://feeds.feedburner.com/danstroot/fZJa

# Pagination and Permalinks
paginate:       5       # Posts per page on the blog index
pagination_dir: blog    # Directory base for pagination URLs eg. /blog/page/2/
permalink:      pretty  # pretty/date

# Server
destination:    ./_site
exclude:        ["LICENSE", ".editorconfig", ".gitignore", "Gruntfile.js", "s3_website.yml", "package.json", "node_modules", "README.md", "TODO.md", "copy_bs.sh", "bootstrap", "less", "validation-report.json", "validation-status.json"]
timezone:       America/Los_Angeles
port:           8080
pygments:       true
markdown:       rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

# ----------------------- #
#      Authors            #
# ----------------------- #

authors:
  dan:
    display_name: Dan Stroot
    gravatar:     b6e0ed5e10ea91f67808629f4ae109f2
    email:        dan@thestroots.com
    web:          http://danstroot.com/
    twitter:      danstroot
    github:       dstroot
    bio: |
      Dan is an avid technologist.
      You can find him on Twitter.

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Disqus ID
disqus_id:           danstroot

# Google Analytics (http://google.com/analytics)
google_analytics_id: UA-44765020-1

# Gauges (http://gaug.es/)
gauges_id:           # Not used

# ----------------------- #
#   Social Settings       #
# ----------------------- #

# Github ID
github_id:            dstroot

# LinkedIn
linkedin_id:          dstroot

# Facebook Like
facebook_id:          danstroot
facebook_like:        true

# Twitter
twitter_id:           danstroot
twitter_tweet_button: true

# Google +1
google_plus_one_id:
google_plus_one: #true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_id:      103150764314035491590
google_plus_hidden:  false

# ----------------------- #
#   Search                #
# ----------------------- #

lunr_search:
  excludes: [rss.xml, atom.xml, index.html, error.html, search.html, robots.txt, search.json, sitemap.xml, stopwords.txt]
  stopwords: "stopwords.txt"
  min_length: 3
