# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:           Dan Stroot
url:            http://danstroot.com
root:           /  # If publishing to a subdirectory as in http://site.com/project set 'root: /project'
title:          Dan Stroot's Personal Blog
subtitle:       # Not used

# Pagination and Permalinks
paginate:       5       # Posts per page on the blog index
pagination_dir: blog    # Directory base for pagination URLs eg. /blog/page/2/
permalink:      pretty

# Server
destination:    ./_site
exclude:        [".editorconfig", ".gitignore", "Gruntfile.js", "s3_website.yml", "package.json", "node_modules", "README.md", "bootstrap", "validation-staus.json"]
timezone:       America/Los_Angeles
port:           8080
pygments:       true

# ----------------------- #
#      Authors            #
# ----------------------- #

authors:
  dan:
    display_name: Dan Stroot
    gravatar:     
    email:        dan@thestroots.com
    web:          http://danstroot.com/
    twitter:      danstroot
    github:       dstroot
    bio: |
      Dan is an avid technologist.
      You can find him on Twitter.

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Disqus ID
disqus_id:        # 

# Google Analytics (http://google.com/analytics)
google_analytics_id:

# Gauges (http://gaug.es/)
gauges_id:        # Not used

# ----------------------- #
#   Social Settings       #
# ----------------------- #

# LinkedIn
linkedin_id:  

# Facebook Like
facebook_id:  
facebook_like: false

# Twitter
twitter_id:  
twitter_tweet_button: false

# Google +1
google_plus_one_id:
google_plus_one: #true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_id: 
google_plus_hidden: false
